### ISSUE TITLE
URLs with .(dot) in its path are getting ignored

### ISSUE THREAD

**Issue by VasanthThoraliKumaran** [nuxt-modules/sitemap#117]
### Describe the bug

- I have a dynamic page structure with URLs having .(dot) in their paths, such as `/my/url/[foo.bar].vue`
- I can see the **./dist** directory contains pre-rendering of all pages. However, I noticed that the URLs containing a dot (.) within their names (for instance, foo.bar in the URL /my/url/foo.bar/) are not being added to the sitemap.xml automatically.
- Upon attempting to manually include these dot-containing URLs in the sitemap, It's getting added.

Also, I have noticed that pre-rendered URLs containing dots are being filtered in [prerender.ts](https://github.com/harlan-zw/nuxt-simple-sitemap/blob/main/src/prerender.ts). Could you kindly clarify whether this filtration is intended to exclude non-HTML files or if there is another reason behind filtering such URLs?

### System / Nuxt Info
my nitro config in nuxt.config.js file
```
nitro: {
    preset: "cloudflare-pages",
    node: true,
    minify: true,
    prerender: {
      concurrency: 1,
      crawlLinks: true,
    }
  }
```

**Comment by harlan-zw** [comment]
This is indeed a bug, will try and fix it soon.

**Comment by harlan-zw** [comment]
Should be fixed in 3.1.7.

Thanks for the issue :)

**Comment by VasanthThoraliKumaran** [comment]
@harlan-zw v3.1.7 ignores all dynamic page URLs and also lastmod is missing in existing sitemap URLs.  I tried `autoLastmod: true` but still the same. Can you pls look at it?

**Comment by harlan-zw** [comment]
> @harlan-zw v3.1.7 ignores all dynamic page URLs and also lastmod is missing in existing sitemap URLs. I tried `autoLastmod: true` but still the same. Can you pls look at it?

My tests are passing on these, are you able to provide a reproduction?

https://stackblitz.com/edit/nuxt-starter-dyraxc?file=server%2Fapi%2F_sitemap-urls.ts

**Comment by VasanthThoraliKumaran** [comment]
@harlan-zw It's working now! Had some cache issue on my side. Thanks for the fix :)

**Comment by harlan-zw** [comment]
Apologies @VasanthThoraliKumaran, looks like my tests are flaky. A fix is available in 3.2.2.

**Comment by VasanthThoraliKumaran** [comment]
@harlan-zw Ohh. I was struggling to make it work :)

**Comment by haugero** [comment]
Hi @VasanthThoraliKumaran 
I see this issue has been closed but it seems that your problem has not been fixed, right?
I write to you as I have the same problem with dots in slugs of my prerendered pages and the pages not appearing in the sitemap.xml
Have you found a solution in the meantime?

**Comment by harlan-zw** [comment]
Please provide a reproduction if you're still having issues.

**Comment by haugero** [comment]
@harlan-zw Thank you for your feedback and sorry for my late response.

I have created a simple example application for reproduction.
You can find it here: https://github.com/haugero/nuxt-sitemap-issue
If you run "npm run generate" you can see that the route "/partner/partner.2" is added as prerendered route (in nuxt hook) BUT it does not occur in the sitemap.xml afterwards. The other route w/o a dot is added correctly.

Would be nice if you could help me with this issue. Thanks in advance!

**Comment by haugero** [comment]
Hi @harlan-zw 
Thank you very much for your changes!
When do you think your changes will be released?

**Comment by harlan-zw** [comment]
I've just pushed up @nuxtjs/sitemap@6.0.0-beta.1 which includes this fix.
