### ISSUE TITLE
I18n `prefix_and_default` strategy issues

### ISSUE THREAD

**Issue by tmlmt** [nuxt-modules/sitemap#166]
### Describe the bug

Dynamic urls returned with `_i18nTransform: true` are only added to the default locale sitemap in its form with prefix

### Reproduction

https://stackblitz.com/edit/github-vty3pl-m6axfg?file=server%2Fapi%2F__sitemap__%2Fwiki.ts

Observe that in the default locale sitemap (/en-US-sitemap.xml) that /wiki pages are only added without prefix. 

### System / Nuxt Info

```Shell
------------------------------
- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.8.1
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      devtools, modules, content, i18n, routeRules, site, sitemap
- Runtime Modules:  @nuxtjs/i18n@8.0.0-rc.5, @nuxt/content@2.8.5, nuxt-simple-sitemap@4.0.1
- Build Modules:    -
------------------------------
```

**Comment by harlan-zw** [comment]
This seems to be fixed with the latest version. https://stackblitz.com/edit/github-vty3pl-rgjxm9?file=server%2Fapi%2F__sitemap__%2Fwiki.ts

**Comment by tmlmt** [comment]
No, doesn't seem like it's fixed. In that Stackblitz you just posted, in the `/en-US-sitemap.xml`, I can only see:
```
/wiki/page1
/wiki/page2
```
It should be:
```
/en/wiki/page1
/en/wiki/page2
/wiki/page1
/wiki/page2
```

**Comment by harlan-zw** [comment]
This is not the correct behavior, we should only add canonical URLs to a sitemap. Otherwise you're wasting crawl credit visiting URLs that won't get indexed.

**Comment by tmlmt** [comment]
Thanks for the explanation. Then this very issue is an incorrect one to begin with, and there is a bug, as although dynamic urls only see their canonical URLs added to the default locale sitemap, pages on the other hand see both their canonical URLs and the default locale prefixed url added to it. 
See: https://stackblitz.com/edit/github-vty3pl-rwy2pc?file=nuxt.config.ts, going to the default (EN) sitemap, there's both `/somePage` and `/en/somePage`

**Comment by PabloGBarcelo** [comment]
@harlan-zw wasn't this issue fixed in version 4.1.8?

**Comment by harlan-zw** [comment]
This is still an issue:

![image](https://github.com/nuxt-modules/sitemap/assets/5326365/efc4d16e-7f34-4717-a898-d5e2acaea462)

The sitemap should contain either:
- http://localhost:3000/somePage	
- http://localhost:3000/en/somePage

This is because we only have one of these as a canonical URL and we should only have canonical URLs in the sitemap. I made the call above to prefer the non-prefixed version, so we shouldn't see http://localhost:3000/en/somePage

Here is an updated reproduction: https://stackblitz.com/edit/github-vty3pl-r9uo6w?file=nuxt.config.ts

If anyone wants to take a look :pray: Otherwise will try sort this soon

**Comment by harlan-zw** [comment]
This should be finally fixed in [v5.3.0](https://github.com/nuxt-modules/sitemap/releases/tag/v5.3.0).
