### ISSUE TITLE
help: Why does the URL automatically end with /? I haven't set trailingSlash

### ISSUE THREAD

**Issue by WooHoo-Wu** [nuxt-modules/sitemap#349]
### 📚 What are you trying to do?

<img width="813" alt="image" src="https://github.com/user-attachments/assets/c9489b7b-a28c-40b9-95ba-c7a7ba928e12">
![image](https://github.com/user-attachments/assets/e9b3cb2a-d8d8-4b41-95fd-91c2be16fe9f)

**Comment by WooHoo-Wu** [comment]
I use @nuxtjs/seo, the latest sitemap version

**Comment by WooHoo-Wu** [comment]
help me ！！！

**Comment by WooHoo-Wu** [comment]
When I set differentDomains: true, you will add /. I can't remove it in hooks('sitemap:resolved'). I need to set differentDomains: true, and the sitemap URL does not need to be followed by /. What should I do?

**Comment by WooHoo-Wu** [comment]
Version v5.2.1 is OK, but nuxtjs/seo will update your version, which leads to this problem

**Comment by harlan-zw** [comment]
Can you make a reproduction? The only thing I can think of is that you've set the trailing slashes option somewhere.

**Comment by WooHoo-Wu** [comment]
reproduction:
https://stackblitz.com/edit/nuxt-starter-h71ojo?file=package.json

result：
<img width="769" alt="image" src="https://github.com/user-attachments/assets/df837770-cb89-497e-93d1-32ae7e9f512b">

Please help me🥺

**Comment by WooHoo-Wu** [comment]
https://nuxtstarterh71ojo-geb4--3000--9569b1ab.local-credentialless.webcontainer.io/__sitemap__/hr.xml

The above link can reproduce this problem. I didn't set anything. Shouldn't it remove the trailing slash by default?

It adds it now and I can't remove it? No matter what method I use, hooks can't remove it

**Comment by harlan-zw** [comment]
Yes I can confirm it's a bug, I'll take a look when I  have a chance.

**Comment by WooHoo-Wu** [comment]
Ok please asap I need it badly

**Comment by WooHoo-Wu** [comment]
![image](https://github.com/user-attachments/assets/c3a454ef-beec-453e-b141-2352f9fcb8b5)

I debugged it myself and found that it was the problem at this location. I hope it will be helpful.

**Comment by harlan-zw** [comment]
Should be fixed in 6.0.0-beta.5 :+1:

**Comment by WooHoo-Wu** [comment]
The @nuxtjs/seo module version is still 6.0.0-beta.2. I reinstalled @nuxtjs/sitemap and changed its version to 6.0.0-beta.5, but it still does not take effect in the production environment. What should I do?

![image](https://github.com/user-attachments/assets/63bee4b2-77d1-4caf-a9e5-38e5e96cfb40)
![image](https://github.com/user-attachments/assets/7509d68f-bd56-43fe-97b5-c37bcced92b5)

**Comment by WooHoo-Wu** [comment]
https://stackblitz.com/edit/nuxt-starter-h71ojo?file=package.json,nuxt.config.ts

It seems that the repair was not successful

**Comment by harlan-zw** [comment]
Seems fine to me, please make sure you update your lock file.

![image](https://github.com/user-attachments/assets/38436d96-44e7-4cb2-a4cc-eaf221358194)

![image](https://github.com/user-attachments/assets/2009b38c-4f8c-4029-86c8-339a55968fbd)

**Comment by WooHoo-Wu** [comment]
thanks
