### ISSUE TITLE
`sitemap:resolved` is not assignable to parameter of type `HookKeys<NitroRuntimeHooks>`

### ISSUE THREAD

**Issue by olivervorasai** [nuxt-modules/sitemap#93]
### Describe the bug

When using the Nitro hook `sitemap:resolved` the following Typescript error appears in VSCode:

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/6283219/6328e2a3-2819-4800-ba47-ce51cab1c7f1)

- I have run `npm run postinstall` to generate types.
- I have tried restarted VSCode.
- I am on Vue Language Features (Volar) v1.8.4 with Takeover mode enabled.

### Reproduction

I am not sure if Typescript errors show properly in stackblitz but here is a reproduction anyways:
https://stackblitz.com/edit/nuxt-starter-fs6gug?file=server%2Fplugins%2Fsitemaps.ts

### System / Nuxt Info

```Shell
Nuxt project info:
------------------------------
- Operating System: Windows_NT
- Node Version:     v16.15.1
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  npm@8.11.0
- Builder:          vite
- User Config:      devtools, modules, sitemap
- Runtime Modules:  nuxt-simple-sitemap@3.0.9
- Build Modules:    -
------------------------------


VSCode Info:
------------------------------
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
------------------------------
```

### Notes
This is a Typescript only issue and the code works fine otherwise.

**Comment by harlan-zw** [comment]
Hey @olivervorasai, thanks for the issue.

I think this might be fixed in 3.0.10: https://stackblitz.com/edit/nuxt-starter-qj13lu?file=server%2Fplugins%2Fsitemaps.ts

Can you confirm on your end?

**Comment by olivervorasai** [comment]
> Hey @olivervorasai, thanks for the issue.
> 
> I think this might be fixed in 3.0.10: https://stackblitz.com/edit/nuxt-starter-qj13lu?file=server%2Fplugins%2Fsitemaps.ts
> 
> Can you confirm on your end?

I cloned this stackblitz and ran it locally and I am still seeing the typescript error. It is very strange since it seems to work fine on stackblitz.

Steps:

1. Clone stackblitz with 3.0.10
2. Delete `.nuxt` folder
3. `npm i`
4. Reload VSCode
5. Error still persists

**Comment by olivervorasai** [comment]
Workaround: using the hooks in nuxt.config.ts instead of in a plugin works fine. Note: this is the recommended way in the documentation.
https://nuxtseo.com/sitemap/api/nuxt-hooks

**Comment by harlan-zw** [comment]
Thanks for the update @olivervorasai.

Do you think this can be closed or is there somewhere else the types aren't working?

**Comment by olivervorasai** [comment]
@harlan-zw Its the Nitro hooks that are not working when used in defineNitroPlugin. The Nuxt hooks work fine when define in nuxt.config.ts.

**Comment by harlan-zw** [comment]
Hm maybe in 3.2.2 this is fixed :crossed_fingers:

**Comment by olivervorasai** [comment]
@harlan-zw Unfortunately it is still not fixed. 

1. I tested again by making a brand new Nuxt app locally via `npx nuxi@latest init my-app` and `npm install -D nuxt-simple-sitemap`.
2. `postinstall` ran and re-generated the types.
3. I restart VSCode just in case.

I still see this message:
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/6283219/1df7805e-fba8-4beb-a344-4053171bbf74)

VSCode autocomplete sees these as available hooks:
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/6283219/2c901b2a-8616-45f1-854c-e8579443859d)

**Comment by ybabenkoJapp** [comment]
@harlan-zw @olivervorasai  It is still not fixed until now 

 "@nuxtjs/sitemap": "^5.1.4",
 "nuxt": "^3.7.3",

**Comment by ybabenkoJapp** [comment]
@harlan-zw do you need any additional information from my side?

**Comment by harlan-zw** [comment]
This should hopefully be fixed in v5.2.0, it seems the nitro types weren't resolving correctly.
